name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 17
        
      - name: Install dependencies
        run: npm ci
        
      - name: Install Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb
      
      
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v2
        with:
          start: npm run test
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 60
          headless: true
          browser: chrome
          
          
          
